package Controller;

import Model.*;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.Initializable;
import javafx.scene.control.*;

import java.io.IOException;
import java.net.URL;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;

public class CreateAppointmentController implements Initializable, LoadableController {

    public Button cancelButton;
    public Button createButton;

    public TextField titleTextField;
    public TextField customerTextField;
    public TextField locationTextField;
    public TextField typeTextField;
    public TextField idTextField;
    public TextField userTextField;

    public TextArea descriptionTextArea;

    public Label idLabel;
    public Label titleLabel;
    public Label locationLabel;
    public Label typeLabel;
    public Label customerLabel;
    public Label userLabel;
    public Label descriptionLabel;
    public Label contactLabel;
    public Label startDateLabel;
    public Label startTimeLabel;
    public Label endTimeLabel;

    public DatePicker startDatePicker;

    public ComboBox startTimePicker;
    public ComboBox endTimePicker;
    public ChoiceBox contactPicker;


    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {

        idLabel.setText(Translator.getTranslation("id"));
        titleLabel.setText(Translator.getTranslation("title"));
        typeLabel.setText(Translator.getTranslation("type"));
        customerLabel.setText(Translator.getTranslation("customerid"));
        userLabel.setText(Translator.getTranslation("userid"));
        descriptionLabel.setText(Translator.getTranslation("description"));
        contactLabel.setText(Translator.getTranslation("contact"));
        startDateLabel.setText(Translator.getTranslation("startdate"));
        startTimeLabel.setText(Translator.getTranslation("starttime"));
        endTimeLabel.setText(Translator.getTranslation("endtime"));

        createButton.setText(Translator.getTranslation("create"));
        cancelButton.setText(Translator.getTranslation("cancel"));

        idTextField.setPromptText(Translator.getTranslation("autogenerated"));

        contactPicker.setItems(UserDao.getAllContacts());

        ObservableList<Integer> hours = FXCollections.observableArrayList();
        ObservableList<String> minutes = FXCollections.observableArrayList();
        hours.addAll(8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22);
        minutes.addAll("00", "30");
        ObservableList<String> times = FXCollections.observableArrayList();

        // get offset
        LocalDateTime curr = LocalDateTime.now();
        ZonedDateTime buisnessTime = curr.atZone(ZoneId.of("America/New_York"));
        ZonedDateTime userTime = curr.atZone(UserDao.getZone());
        int diffHours = (int) Duration.between(buisnessTime, userTime).toHours();
        for (int hour : hours) {
            for (String minute : minutes) {
                int offsetHours = (hour - diffHours);
                if (offsetHours < 10) {
                    times.add("0" + offsetHours + ":" + minute);
                } else {
                    times.add((offsetHours) + ":" + minute);
                }
                if (hour == 22) { break; }
            }
        }
        startTimePicker.setItems(times);
        endTimePicker.setItems(times);
    }

    @Override
    public void load(Appointment appointment) {

    }

    @Override
    public void load(Customer customer) {

    }

    public void handleCreate(ActionEvent actionEvent) throws Exception {
        String title;
        String type;
        String description;
        String location;
        int customerId;
        int userId;
        int contact;
        LocalDateTime startDateTime;
        LocalDateTime endDateTime;
        try {
            /** get appointment title **/
            try {
                title = titleTextField.getText();
            } catch (Exception e) {
                throw new Exception("titleerror");
            }
            /** if title is empty throw exception **/
            if (title.length() == 0) { throw new Exception("titleblank"); }

            /** get appointment type **/
            try {
                type = typeTextField.getText();
            } catch (Exception e) {
                throw new Exception("typeerror");
            }
            /** if type is empty throw exception **/
            if (type.length() == 0) { throw new Exception("typeblank"); }

            /** get appointment description **/
            try {
                description = descriptionTextArea.getText();
            } catch (Exception e) {
                throw new Exception("descriptionerror");
            }
            /** if description throw exception **/
            if (description.length() == 0) { throw new Exception("descriptionblank"); };

            /** get appointment location **/
            try {
                location = locationTextField.getText();
            } catch (Exception e) {
                throw new Exception("locationerror");
            }
            /** if location is blank throw exception **/
            if (location.length() == 0) { throw new Exception("locationblank"); }

            /** get customer_id for appointment **/
            /** throw exception if not parseable to integer **/
            try {
                customerId = Integer.parseInt(customerTextField.getText());
            } catch (Exception e) {
                throw new Exception("customererror");
            }

            /** get user_id for appointment **/
            /** throw exception if not parseable to integer **/
            try {
                userId = Integer.parseInt(userTextField.getText());
            } catch (Exception e) {
                throw new Exception("usererror");
            }

            /** get Contact for appointment **/
            /** throw exception if no contact is selected **/
            try {
                contact = ((Contact) contactPicker.getValue()).getId();
            } catch (Exception e) {
                throw new Exception("contacterror");
            }

            /** get start time for appointment **/
            /** throw exception if start time isn't valid **/
            try {
                String startDate = startDatePicker.getValue().toString();
                String startTime = startTimePicker.getValue().toString();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                startDateTime = LocalDateTime.parse(startDate + " " + startTime, formatter).atZone(ZoneId.of("UTC")).toLocalDateTime();
            } catch (Exception e) {
                throw new Exception("starttimeerror");
            }
            if (startDateTime.getDayOfWeek().toString() == "SATURDAY" || startDateTime.getDayOfWeek().toString() == "SUNDAY") {
                throw new Exception("starttimeweekend");
            };

            /** get end time for appoint **/
            /** throw exception if end time isn't valid **/
            try {
                String endDate = startDatePicker.getValue().toString();
                String endTime = endTimePicker.getValue().toString();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                endDateTime = LocalDateTime.parse(endDate + " " + endTime, formatter).atZone(ZoneId.of("UTC")).toLocalDateTime();
            } catch (Exception e) {
                throw new Exception("endtimeerror");
            }
            if (endDateTime.getDayOfWeek().toString() == "SATURDAY" || endDateTime.getDayOfWeek().toString() == "SUNDAY") {
                throw new Exception("endtimeweekend");
            };

            /** throw exception if endDate is before start date **/
            if (endDateTime.isBefore(startDateTime)) {
                throw new Exception("endtimebefore");
            }
            /** create new appointment from user input **/
            Appointment newAppointment = new Appointment(title, description, location, type,
                    startDateTime,
                    endDateTime,
                    customerId, userId, contact);
            /** insert new appointment into database **/
            UserDao.createAppointment(newAppointment);
            /** return to main menu **/
            ViewCreator.createViewWithAppointment("mainmenu", "MainMenu", 900, 500, actionEvent, this, newAppointment);
        } catch (Exception e) {
            PopUpBox.displayError(e.getMessage());
        }
    }

    public void handleCancel(ActionEvent actionEvent) throws IOException {
        ViewCreator.createView("mainmenu", "MainMenu", 900, 500, actionEvent, this);
    }
}
